#ifndef HTTPSTATUS_HPP
#define HTTPSTATUS_HPP

#include <string>

enum STATUS_CODE{
	//Success
	OK = 200,
	CREATED = 201,
	//Error client
	BAD_REQUEST = 400,
	NOT_FOUND = 404,
	LENGTH_REQUIRED = 411,
	//Error server
	INTERNAL_SERVER_ERROR = 500,
	NOT_IMPLEMENTED = 501,
	SERVICE_UNAVAILABLE = 503,
	HTTP_VERSION_NOT_SUPPORTED = 505
};

#endif